import { InstitutionType } from '../../constants/enums';
import { Institution } from '../../institutions/insititution.entity';
import { MigrationInterface, QueryRunner } from 'typeorm';

export class PopulateInstitutionTable1710553757443
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const fedUnis = [
      {
        name: 'Abubakar Tafawa Balewa University',
        state: 'Bauchi',
        abbreviation: 'ATBU',
        city: 'Bauchi',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Ahmadu Bello University',
        state: 'Kaduna',
        abbreviation: 'ABU',
        city: 'Zaria',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Alex Ekwueme Federal University Ndufu Alike Ikwo',
        state: 'Ebonyi',
        abbreviation: 'AE-FUNAI',
        city: 'Ikwo',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Bayero University',
        state: 'Kano',
        abbreviation: 'BUK',
        city: 'Kano',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University of Agriculture, Abeokuta',
        state: 'Ogun',
        abbreviation: 'FUNAAB',
        city: 'Abeokuta',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University Birnin Kebbi',
        state: 'Kebbi',
        abbreviation: 'FUBK',
        city: 'Birnin Kebbi',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University Dutse',
        state: 'Jigawa',
        abbreviation: 'FUD',
        city: 'Dutse',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University Dutsin-Ma',
        state: 'Katsina',
        abbreviation: 'FUDM',
        city: 'Dutsin-Ma',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University Gashua',
        state: 'Yobe',
        abbreviation: 'FUGASHUA',
        city: 'Gashua',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University Gusau',
        state: 'Zamfara',
        abbreviation: 'FUGUS',
        city: 'Gusau',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University Kashere',
        state: 'Gombe',
        abbreviation: 'FUK',
        city: 'Kashere',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University Lokoja',
        state: 'Kogi',
        abbreviation: 'FUL',
        city: 'Lokoja',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University of Lafia',
        state: 'Nasarawa',
        abbreviation: 'FULAFIA',
        city: 'Lafia',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University of Petroleum Resources Effurun',
        state: 'Delta',
        abbreviation: 'FUPRE',
        city: 'Effurun',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University of Technology Akure',
        state: 'Ondo',
        abbreviation: 'FUTA',
        city: 'Akure',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University of Technology Minna',
        state: 'Niger',
        abbreviation: 'FUTMIN',
        city: 'Minna',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University of Technology Owerri',
        state: 'Imo',
        abbreviation: 'FUTO',
        city: 'Owerri',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University Otuoke',
        state: 'Bayelsa',
        abbreviation: 'FUO',
        city: 'Otuoke',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University Oye-Ekiti',
        state: 'Ekiti',
        abbreviation: 'FUOYE',
        city: 'Oye-Ekiti',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University Wukari',
        state: 'Taraba',
        abbreviation: 'FUW',
        city: 'Wukari',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Michael Okpara University of Agriculture, Umudike',
        state: 'Abia',
        abbreviation: 'MOUAU',
        city: 'Umudike',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Modibbo Adama University, Yola',
        state: 'Adamawa',
        abbreviation: 'MAU',
        city: 'Yola',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'National Open University of Nigeria',
        state: 'Lagos',
        abbreviation: 'NOUN',
        city: 'Victoria Island',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Nnamdi Azikiwe University',
        state: 'Anambra',
        abbreviation: 'UNIZIK',
        city: 'Awka',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Obafemi Awolowo University',
        state: 'Osun',
        abbreviation: 'OAU',
        city: 'Ile Ife',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'University of Abuja',
        state: 'Federal Capital Territory',
        abbreviation: 'UNIABUJA',
        city: 'Gwagwalada',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'University of Agriculture, Makurdi',
        state: 'Benue',
        abbreviation: 'UAM',
        city: 'Makurdi',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'University of Benin',
        state: 'Edo',
        abbreviation: 'UNIBEN',
        city: 'Benin city',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'University of Calabar',
        state: 'Cross River',
        abbreviation: 'UNICAL',
        city: 'Calabar',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'University of Ibadan',
        state: 'Oyo',
        abbreviation: 'UI',
        city: 'Ibadan',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'University of Ilorin',
        state: 'Kwara',
        abbreviation: 'UNILORIN',
        city: 'Ilorin',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'University of Jos',
        state: 'Plateau',
        abbreviation: 'UNIJOS',
        city: 'Jos',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'University of Lagos',
        state: 'Lagos',
        abbreviation: 'UNILAG',
        city: 'Akoka',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'University of Maiduguri',
        state: 'Borno',
        abbreviation: 'UNIMAID',
        city: 'Maiduguri',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'University of Nigeria, Nsukka',
        state: 'Enugu',
        abbreviation: 'UNN',
        city: 'Nsukka',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'University of Port Harcourt',
        state: 'Rivers',
        abbreviation: 'UNIPORT',
        city: 'Port Harcourt',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'University of Uyo',
        state: 'Akwa Ibom',
        abbreviation: 'UNIUYO',
        city: 'Uyo',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Federal University of Technology Ikot Abasi',
        state: 'Akwa Ibom',
        abbreviation: 'FUTIA',
        city: 'Ikot-Abasi',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Usmanu Danfodiyo University',
        state: 'Sokoto',
        abbreviation: 'UDUS',
        city: 'Sokoto',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
    ];

    const stateUnis = [
      {
        name: 'Abia State University',
        state: 'Abia',
        abbreviation: 'ABSU',
        city: 'Uturu',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Adamawa State University',
        state: 'Adamawa',
        abbreviation: 'ADSU',
        city: 'Mubi',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Adekunle Ajasin University',
        state: 'Ondo',
        abbreviation: 'AAUA',
        city: 'Akungba-Akoko',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Akwa Ibom State University (formerly Akwa Ibom State University of Science and Technology)',
        state: 'Akwa Ibom',
        abbreviation: 'AKSU',
        city: 'Uyo',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Aliko Dangote University of Science and Technology',
        state: 'Kano',
        abbreviation: 'ADUSTECH',
        city: 'Wudil',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Ambrose Alli University',
        state: 'Edo',
        abbreviation: 'AAU',
        city: 'Ekpoma',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Bauchi State University',
        state: 'Bauchi',
        abbreviation: 'BASUG',
        city: 'Gadau',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Bayelsa Medical University',
        state: 'Bayelsa',
        abbreviation: 'BMU',
        city: 'Yenagoa',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Benue State University',
        state: 'Benue',
        abbreviation: 'BSU',
        city: 'Makurdi',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Borno State University',
        state: 'Borno',
        abbreviation: 'BOSU',
        city: 'Maiduguri',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Bukar Abba Ibrahim University',
        state: 'Yobe',
        abbreviation: 'YSU',
        city: 'Damaturu',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Chukwuemeka Odumegwu Ojukwu University (formerly Anambra State University)',
        state: 'Anambra',
        abbreviation: 'ANSU',
        city: 'Uli',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'University of Cross River State (formerly Cross River University of Technology)',
        state: 'Cross River',
        abbreviation: 'UNICROSS',
        city: 'Ekpo-Abasi, Calabar',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Delta State University, Abraka',
        state: 'Delta',
        abbreviation: 'DELSU',
        city: 'Abraka',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Delta State University of Science and Technology, Ozoro',
        state: 'Delta',
        abbreviation: 'DSPZ',
        city: 'Ozoro',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Dennis Osadebe University, Asaba',
        state: 'Delta',
        abbreviation: 'DOU',
        city: 'Asaba',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Ebonyi State University',
        state: 'Ebonyi',
        abbreviation: 'EBSU',
        city: 'Abakaliki',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Edo State University',
        state: 'Edo',
        abbreviation: 'EDSU',
        city: 'Iyamho',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Ekiti State University',
        state: 'Ekiti',
        abbreviation: 'ESUAD',
        city: 'Ado Ekiti',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Enugu State University of Science and Technology (formerly Anambra State University of Technology)',
        state: 'Enugu',
        abbreviation: 'ESUT',
        city: 'Enugu',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Gombe State University',
        state: 'Gombe',
        abbreviation: 'GSU',
        city: 'Gombe',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Gombe State University of Science and Technology',
        state: 'Gombe',
        abbreviation: 'GSUST',
        city: 'Kumo',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Ibrahim Badamasi Babangida University',
        state: 'Niger',
        abbreviation: 'IBBUL',
        city: 'Lapai',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Ignatius Ajuru University of Education',
        state: 'Rivers',
        abbreviation: 'IAUE',
        city: 'Port Harcourt',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Imo State University',
        state: 'Imo',
        abbreviation: 'IMSU',
        city: 'Owerri',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Kaduna State University',
        state: 'Kaduna',
        abbreviation: 'KASU',
        city: 'Kaduna',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Kebbi State University of Science and Technology',
        state: 'Kebbi',
        abbreviation: 'KSUSTA',
        city: 'Aliero',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Prince Abubakar Audu University',
        state: 'Kogi',
        abbreviation: 'PAAU',
        city: 'Anyigba',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Kwara State University',
        state: 'Kwara',
        abbreviation: 'KWASU',
        city: 'Malete',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Ladoke Akintola University of Technology',
        state: 'Oyo',
        abbreviation: 'LAUTECH',
        city: 'Ogbomoso',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Lagos State University',
        state: 'Lagos',
        abbreviation: 'LASU',
        city: 'Ojo',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Lagos State University of Education',
        state: 'Lagos',
        abbreviation: 'LASUED',
        city: 'Ijanikin',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Lagos State University of Science and Technology',
        state: 'Lagos',
        abbreviation: 'LASUST',
        city: 'Ikorodu',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Nasarawa State University',
        state: 'Nasarawa',
        abbreviation: 'NSUK',
        city: 'Keffi',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Niger Delta University',
        state: 'Bayelsa',
        abbreviation: 'NDU',
        city: 'Amassoma',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Olabisi Onabanjo University',
        state: 'Ogun',
        abbreviation: 'OOU',
        city: 'Ago-Iwoye',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Olusegun Agagu University of Science and Technology',
        state: 'Ondo',
        abbreviation: 'OAUST',
        city: 'Okitipupa',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Osun State University',
        state: 'Osun',
        abbreviation: 'UNIOSUN',
        city: 'Osogbo',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Plateau State University',
        state: 'Plateau',
        abbreviation: 'PLASU',
        city: 'Bokkos',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Rivers State University',
        state: 'Rivers',
        abbreviation: 'RIVSU',
        city: 'Port Harcourt',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Sule Lamido University',
        state: 'Jigawa',
        abbreviation: 'SLU',
        city: 'Kafin-Hausa',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Tai Solarin University of Education',
        state: 'Ogun',
        abbreviation: 'TASUED',
        city: 'Ijebu Ode',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Taraba State University',
        state: 'Taraba',
        abbreviation: 'TSU',
        city: 'Jalingo',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: "Umaru Musa Yar'adua University",
        state: 'Katsina',
        abbreviation: 'UMYU',
        city: 'Katsina',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Sokoto State University',
        state: 'Sokoto',
        abbreviation: 'SSU',
        city: 'Sokoto',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'University of Delta, Agbor',
        state: 'Delta',
        abbreviation: 'UNIDEL',
        city: 'Agbor',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Yusuf Maitama Sule University Kano',
        state: 'Kano',
        abbreviation: 'YUMSUK',
        city: 'Kano',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
      {
        name: 'Zamfara State University',
        state: 'Zamfara',
        abbreviation: 'ZSU',
        city: 'Talata Mafara',
        type: InstitutionType.University,
        country: 'Nigeria',
      },
    ];

    console.log('Universities Length: ', fedUnis.length);

    const institutions = [...fedUnis, ...stateUnis];

    const repo = queryRunner.manager.getRepository(Institution);

    // Loop through the universities array
    for (const university of institutions) {
      repo.insert(university);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.clearTable('institution');
  }
}
